import Head from "next/head";
import Headerlanding from "../common/headerlanding";

export default function LayoutUser({ children, user={} }) {
  console.log("Layout user",user);
  return (
    <>
      <Head>
        <title>Atlas Chiropract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Headerlanding user={user}/>
        <main>{children}</main>
      </body>
    </>
  );
}
