import Head from "next/head";
import Footer from "../common/footer";
import Header from "../common/header";

export default function Layout({ children, user={} }) {
  return (
    <>
      <Head>
        <title>Atlas Chiropract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header user={user}/>
        <main>{children}</main>
        <Footer />
      </body>
    </>
  );
}
