

export default function LayoutB({ children }) {
  return (
    <>
      <Head>
        <title>Atlas Chiropract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-grey">
        <main>{children}</main>
      </body>
    </>
  );
}
