import Head from "next/head";
import Headerlanding from "./headerlanding";

export default function LayoutB({ children }) {
  return (
    <html>
      <Head>
        <title>Atlas Chiropract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
          
        <main>{children}</main>
      </body>
    </html>
  );
}
